### ISSUE TITLE
Encrypted response using direct_post.jwt also includes unencrypted data

### ISSUE THREAD

**Issue by Aaargh20318** [eu-digital-identity-wallet/eudi-lib-ios-siop-openid4vp-swift#75]
When using `response_mode=direct_post.jwt` and `response_type=vp_token` the resulting response contains both the encrypted `response` parameter and the unencrypted `vp_token`.  This seems kind of self-defeating. 

The data is encrypted here: https://github.com/eu-digital-identity-wallet/eudi-lib-ios-siop-openid4vp-swift/blob/27fd4d53cbaa20056c56083e4d8efbae67f1ea23/Sources/Main/Services/AuthorisationService.swift#L74

And then the encrypted response is merged into the unencrypted data here: https://github.com/eu-digital-identity-wallet/eudi-lib-ios-siop-openid4vp-swift/blob/27fd4d53cbaa20056c56083e4d8efbae67f1ea23/Sources/Main/Services/AuthorisationService.swift#L76-L82

I would expect the encrypted response to replace the unencrypted response, instead of being merged with it.

**Comment by dtsiflit** [comment]
Thank you so much for bringing this up @Aaargh20318 . We will get a PR submitted.
