### ISSUE TITLE
Support for redirect_uri type for client_id_scheme parameter

### ISSUE THREAD

**Issue by Reydder** [eu-digital-identity-wallet/eudi-lib-ios-siop-openid4vp-swift#78]
The `redirect_uri` type isn't added to the `ClientIdSchemeSupported` enum. 

https://github.com/eu-digital-identity-wallet/eudi-lib-ios-siop-openid4vp-swift/blob/main/Sources/Entities/ClientMetaData/SupportedClientIdScheme.swift

If this client_id_scheme is implemented, could it also be handled in the `getClient()` method of the `ValidatedSiopOpenId4VPRequest`?

https://github.com/eu-digital-identity-wallet/eudi-lib-ios-siop-openid4vp-swift/blob/main/Sources/Entities/Validated/ValidatedSiopOpenId4VPRequest.swift

**Comment by dtsiflit** [comment]
Thank you very much for opening this! PR #79 addresess it. We'll get it merged in over the next couple of days.
